### ISSUE TITLE
Fase 0: Preparação do Ambiente 

### ISSUE THREAD

**Issue by david-jc-br** [david-jc-br/ProjetoEngenhariaDeSoftware#1]
- [x] #1 Alterar o ReadMe. #4 da planilha. ----- "Tenha no README um seção chamada TECNOLOGIAS UTILIZADAS na qual deverá estar descrita a liguagem utilizada e versão, Banco de Dados utilizado e Versão, Servidor utilizado no desenvolvimento e versão, dentre outras tecnologias utilizadas" 
- [x] - [ ] #1 Especificar as características que devem ser obedecidas ao descrever os requisitos do projeto. #5 da planilha. Além disto, descreva pelo menos três regras que o documento de requisitos seguirá. O aluno deverá criar um documento chamado "Regras de Verificação e Analise de Requisitos" e armazená-lo na pasta denominada "Padrões Adotados".
- [x] #1 Usar tags e releases #6 da planilha.
