### ISSUE TITLE
Fase 1:  Especificação do Produto

### ISSUE THREAD

**Issue by david-jc-br** [david-jc-br/ProjetoEngenhariaDeSoftware#2]
- [x] #8 Identificar Requisitos Funcionais (RF) 
- [x] #9 Identificar Requisitos Não-Funcionais (RNF) 
- [x] #10 Prototipação de Interface 
- [x] #11 Criar diagrama de casos de uso 
- [x] #12 Documentar cenários de caso de uso ************ quase = a #8
- [ ] #14 Criar backlog do produto no GitHub 
- [ ] #15 Garantir rastreabilidade entre itens do backlog do produto e RFs e RNFs
